{% set version = environ.get('CONDA_SPHINXFORTRAN_VERSION',"1.1.1") %}
{% set pkg_buildnum = environ.get('CONDA_SPHINXFORTRAN_BUILDNUM',"0") %}

package:
  name: sphinx-fortran
  version: "{{ version }}"

build:
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .
  number: {{ pkg_buildnum }}

source:
  git_url: https://github.com/VACUMM/sphinx-fortran.git
  git_rev: "{{ version }}"

requirements:
  build:
    - python # >=2.7
    - setuptools
    - sphinx
    - pip
  run:
    - python #>=2.7
    - numpy
    - sphinx
    - six

test:
  imports:
    - sphinxfortran.fortran_domain
    - sphinxfortran.fortran_autodoc

about:
  home: http://sphinx-fortran.readthedocs.org
  license: CeCILL
  summary: Fortran domain and auto-documenter for Sphinx
  dev_url: https://github.com/VACUMM/sphinx-fortran

