name: vacumm

channels:
  - vacumm
  - conda-forge
  - uvcdat
  - defaults
  
dependencies:
  - python >=2.7,<3
  - numpy
  - libgfortran
  - uvcdat
  - matplotlib >=2.0
  - basemap-data-hires
  - cmocean
  - configobj
  - pytz
  - paramiko
  - xlutils
  - seawater
  - pyqt >=4,<=5

