{% set vacumm_data_version = environ.get('CONDA_VACUMM_DATA_VERSION',"1.0") %}
{% set pkg_buildnum = environ.get('CONDA_VACUMM_DATA_BUILDNUM',"0") %}
{% set git_rev = environ.get('CONDA_VACUMM_DATA_GITREV',vacumm_data_version) %}


package:
  name: vacumm-data
  version: "{{ vacumm_data_version }}"

build:
#    script: python setup.py install
    script: python -m pip install --no-deps --ignore-installed .
    number: {{ pkg_buildnum }}
    noarch: python

source:
  path: /home/shom/sraynaud/Dev/forge/vacumm-data
#  git_url: https://github.com/VACUMM/vacumm-data.git
#  {% if git_rev!="HEAD" %}
#  git_rev: {{ git_rev }}
#  {% endif %}

requirements:
  build:
    - pip


about:
  home: https://www.ifremer.fr/vacumm
  summary: Data used by the vacumm python library and its tutorials and tests

