{% set vacumm_version = environ.get('CONDA_VACUMM_VERSION',"3.6.4") %}
{% set pkg_buildnum = environ.get('CONDA_VACUMM_BUILDNUM',"0") %}
{% set git_rev = environ.get('CONDA_VACUMM_GITREV',vacumm_version) %}
{% set git_url = environ.get('CONDA_VACUMM_GITURL',"https://github.com/VACUMM/vacumm.git") %}
#{% set python_version = environ.get('PYTHON_VERSION',2.7) %}
#{% set numpy_version = environ.get('NUMPY_VERSION',1.11) %}


package:
  name: vacumm
  version: "{{ vacumm_version }}"

build:
  number: {{ pkg_buildnum }}
  skip: true  # [win or py3k]

source:
  git_url: {{ git_url }}
  {% if git_rev!="HEAD" %}
  git_rev: {{ git_rev }}
  {% endif %}

requirements:
  build:
    - {{ compiler('fortran') }}
  host:
    - python {{ python }}
    - numpy {{ numpy }}
    - pip
  run:
    - {{ pin_compatible('python') }}
    - {{ pin_compatible('numpy') }}
    - cdms2
    - cdutil
    - genutil
    - matplotlib >=2.0
    - cmocean
    - basemap
    - basemap-data-hires
    - configobj
    - pytz
    - paramiko
    - xlutils
    - seawater
    - scipy

test:
  imports:
    - vacumm
    - vcmq
  requires:
    - pytest
  commands:
    - export UVCDAT_ANONYMOUS_LOG=no && cd test && pytest -x -W ignore test_misc.py test_atime.py test_color.py test_plot.py test_grid.py test_filters.py test_mask.py test_stats.py test_basemap.py test_arakawa.py test_regrid.py test_io.py test_diag.py test_dataset.py
  source_files:
    - test/*.py
    - scripts/test/*
    - data/*

about:
  home: http://www.ifremer.fr/vacumm
  license: CeCiLL-2.1
  license_family: GPL
  license_file: LICENSE
  summary: 'A Python library for ocean sciences'
  description: |
    VACUMM provides generic and specialized tools for the validation of ocean
    models, and more especially the MARS model from IFREMER.
    The heart of VACUMM is a library written mainly in the Python language,
    whose core can be used for the preprocessing and the postprocessing of
    oceanic and atmospheric data coming from models or observations.
    The library for instance also has specialized modules for managing
    outputs from models and making advanced diagnostics.
  doc_url: http://www.ifremer.fr/vacumm
  dev_url: https://github.com/VACUMM/vacumm

extra:
  recipe-maintainers:
    - stefraynaud
