{% set vacumm_version = environ.get('CONDA_VACUMM_VERSION',"3.3.0") %}
{% set pkg_buildnum = environ.get('CONDA_VACUMM_BUILDNUM',"1") %}
{% set git_rev = environ.get('CONDA_VACUMM_GITREV',vacumm_version) %}


package:
  name: vacumm
  version: "{{ vacumm_version }}"

build:
    script: python setup.py install
    number: {{ pkg_buildnum }}
    
source:
  git_url: https://github.com/VACUMM/vacumm.git
  {% if git_rev!="HEAD" %}
  git_rev: {{ git_rev }}
  {% endif %}

requirements:
  build:
    - python >=2.7,<3
    - setuptools
    - numpy
    - libgfortran
  run:
    - python >=2.7,<3
    - numpy
    - libgfortran
    - uvcdat ==2.8.0
    - configobj
    - pytz
    - paramiko
    - xlutils
    - seawater
    - cmocean
    - basemap-data-hires

test:
  imports:
    - vacumm
    - vcmq

about:
  home: https://www.ifremer.fr/vacumm
  license: CeCILL-A
  summary: A python library for ocean sciences
  
