{% set vacumm_version = environ.get('CONDA_VACUMM',"3.3.0") %}
{% set uvcdat_version = environ.get('CONDA_UVCDAT',"2.8.0")|replace(".", "") %}
{% set pkg_buildnum = environ.get('CONDA_BUILDNUM',"0") %}


package:
  name: vacumm
  version: "{{ vacumm_version }}"

build:
    script: python setup.py install
    #number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
    string: uvcdat{{ uvcdat_version }}_{{ pkg_buildnum }}
    
source:
  git_url: https://github.com/VACUMM/vacumm.git
  git_rev: {{ vacumm_version }}

requirements:
  build:
    - python >=2.7,<3
    - setuptools
    - numpy
    - libgfortran
  run:
    - python >=2.7,<3
    - numpy
    - libgfortran
    - uvcdat
    - configobj
    - pytz
    - paramiko
    - xlutils
    - seawater
    - cmocean

test:
  imports:
    - vacumm
    - vcmq

about:
  home: https://www.ifremer.fr/vacumm
  license: CeCILL-A
  summary: A python library for ocean sciences
  
