{% set vacumm_version = environ.get('CONDA_VACUMM_VERSION',"3.5.0") %}
{% set pkg_buildnum = environ.get('CONDA_VACUMM_BUILDNUM',"0") %}
{% set git_rev = environ.get('CONDA_VACUMM_GITREV',vacumm_version) %}


package:
  name: vacumm
  version: "{{ vacumm_version }}"

build:
    script: python setup.py install
    number: {{ pkg_buildnum }}
    string: np{{ np }}py{{ py }}_{{ pkg_buildnum }}
    
source:
  git_url: https://github.com/VACUMM/vacumm.git
  {% if git_rev!="HEAD" %}
  git_rev: {{ git_rev }}
  {% endif %}

requirements:
  build:
    - setuptools
    - uvcdat
    - matplotlib >=2.0
  run:
    - uvcdat
    - matplotlib >=2.0
    - cmocean
    - basemap-data-hires
    - configobj
    - pytz
    - paramiko
    - xlutils
    - seawater
    - pyqt >=4,<=5

test:
  imports:
    - vacumm
    - vcmq

about:
  home: https://www.ifremer.fr/vacumm
  license: CeCILL-A
  summary: A python library for ocean sciences
  
